### ISSUE TITLE
Something rleated to DB

### ISSUE THREAD

**Issue by loga4m** [Asadbek07/Future-me-clone#1]
![image](https://user-images.githubusercontent.com/74463827/234489960-cdeffabc-6602-49d0-af7c-0639789fbb70.png)

**Comment by asindarov** [comment]
> ![image](https://user-images.githubusercontent.com/74463827/234489960-cdeffabc-6602-49d0-af7c-0639789fbb70.png)

yeah, good one. I forgot to mention in the README.md that this exception might happen because in the initial state the database migrations will not be migrated but the scheduled work will attempt to get data from database which is not ready in the first place if you don't build and run the liquibase container so I suggest you to follow the instructions shown in the README.md regardless of this exception. I will mention this in the README.md later on
